image: Visual Studio 2017

version: 2.0.{build}

before_build:
  - nuget restore
  - ps: |-
      $path = (Get-Item .\Tether\Tether.csproj).FullName
      $csproj = [xml](Get-Content $path)
      $csproj.Project.PropertyGroup.AssemblyVersion = $Env:APPVEYOR_BUILD_VERSION
      $csproj.Project.PropertyGroup.FileVersion = $Env:APPVEYOR_BUILD_VERSION
      $csproj.Save($path)

skip_commits: 
  files:
  - docs/*
  - '**/*.md'

artifacts:
  - path: Tether\bin\debug\net472
    name: Build
    type: zip