image: Visual Studio 2017

version: 2.0.{build}

before_build:
  - nuget restore

assembly_info:
  patch: true
  file: '**\*.csproj'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

skip_commits: 
  files:
  - docs/*
  - '**/*.md'

artifacts:
  - path: Tether\bin\debug\net472
    name: Build
    type: zip