image: Visual Studio 2017

version: 2.0.{build}

before_build:
  - nuget restore

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

skip_commits: 
  files:
  - docs/*
  - '**/*.md'

artifacts:
  - path: Tether\bin\debug\net472
    name: Build
    type: zip